graph LR
  loghub_logstore_b52a375842a2066f5afcb524abd21c8807f7bd33_8a6294["lineage"]
  loghub_logstore_f01251296bd1cfaec37ae9268c5d5b92def773ab_7d5d8d["entity_lineage"]
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae["meta_table_lineage"]
  maxcompute_table_dataworks_analyze_meta_table_lineage_statistics_813fa8["meta_table_lineage_statistics"]
  maxcompute_table_dataworks_analyze_meta_table_lineage_with_user_de670e["meta_table_lineage_with_user"]
  maxcompute_table_dataworks_analyze_rpt_d_table_lineage_87d958["rpt_d_table_lineage"]
  maxcompute_table_dataworks_meta_dwd_d_retained_metadata_lineage_1110e9["dwd_d_retained_metadata_lineage"]
  maxcompute_table_dataworks_meta_ods_d_crawled_metadata_lineage_8053fc["ods_d_crawled_metadata_lineage"]
  maxcompute_table_ecodata_dist_icbu_jspt_meta_table_lineage_view_49caaf["icbu_jspt_meta_table_lineage_view"]
  maxcompute_table_ecodata_dist_vabt_jspt_meta_table_lineage_view_0890ad["vabt_jspt_meta_table_lineage_view"]
  maxcompute_table_fin_data_platform_fin_meta_table_lineage_7b4ec2["fin_meta_table_lineage"]
  mysql_table_22badf3053c1ae316917326ddf761907cb7842ee_6b947f["fin_meta_table_lineage"]
  mysql_table_4d6d25c4647eb187660054a4e2c88da7ffb287e2_dc2323["base_meta_io_schd_relation"]
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_dataworks_analyze_meta_table_lineage_statistics_813fa8
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_dataworks_analyze_meta_table_lineage_with_user_de670e
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_dataworks_analyze_rpt_d_table_lineage_87d958
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_ecodata_dist_icbu_jspt_meta_table_lineage_view_49caaf
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_ecodata_dist_vabt_jspt_meta_table_lineage_view_0890ad
  maxcompute_table_dataworks_analyze_meta_table_lineage_795dae --> maxcompute_table_fin_data_platform_fin_meta_table_lineage_7b4ec2
  maxcompute_table_dataworks_analyze_meta_table_lineage_with_user_de670e --> mysql_table_4d6d25c4647eb187660054a4e2c88da7ffb287e2_dc2323
  maxcompute_table_dataworks_analyze_rpt_d_table_lineage_87d958 --> loghub_logstore_b52a375842a2066f5afcb524abd21c8807f7bd33_8a6294
  maxcompute_table_dataworks_analyze_rpt_d_table_lineage_87d958 --> loghub_logstore_f01251296bd1cfaec37ae9268c5d5b92def773ab_7d5d8d
  maxcompute_table_ecodata_dist_vabt_jspt_meta_table_lineage_view_0890ad --> maxcompute_table_fin_data_platform_fin_meta_table_lineage_7b4ec2
  maxcompute_table_fin_data_platform_fin_meta_table_lineage_7b4ec2 --> mysql_table_22badf3053c1ae316917326ddf761907cb7842ee_6b947f
  loghub_logstore_b52a375842a2066f5afcb524abd21c8807f7bd33_8a6294 --> maxcompute_table_dataworks_meta_ods_d_crawled_metadata_lineage_8053fc
  maxcompute_table_dataworks_meta_ods_d_crawled_metadata_lineage_8053fc --> maxcompute_table_dataworks_meta_dwd_d_retained_metadata_lineage_1110e9