graph LR
  maxcompute_table_cdo_new_webbi_ods_ism_it_software_key_released_df_f22b05["ods_ism_it_software_key_released_df"]
  maxcompute_table_cdo_new_webbi_ods_ism_it_software_software_version_df_7ffc73["ods_ism_it_software_software_version_df"]
  maxcompute_table_cdo_new_webbi_ods_ism_software_soft_curd_df_c94322["ods_ism_software_soft_curd_df"]
  maxcompute_table_xxpt_cdm_dw_dim_is_fin_pl_reve_volume_dept_0eb195["dim_is_fin_pl_reve_volume_dept"]
  maxcompute_table_xxpt_cdm_dw_dim_is_hr_emp_bsc_info_247980["dim_is_hr_emp_bsc_info"]
  maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604["ads_is_it_software_key_released_recycled_df"]
  maxcompute_table_xxpt_it_ads_ads_is_it_software_license_free_statistic_df_de84a9["ads_is_it_software_license_free_statistic_df"]
  maxcompute_table_xxpt_it_ads_ods_ism_it_software_key_pool_df_07e571["ods_ism_it_software_key_pool_df"]
  maxcompute_table_cdo_new_webbi_ods_ism_it_software_key_released_df_f22b05 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_cdo_new_webbi_ods_ism_it_software_software_version_df_7ffc73 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_cdo_new_webbi_ods_ism_software_soft_curd_df_c94322 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_xxpt_cdm_dw_dim_is_fin_pl_reve_volume_dept_0eb195 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_xxpt_cdm_dw_dim_is_hr_emp_bsc_info_247980 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_xxpt_it_ads_ads_is_it_software_license_free_statistic_df_de84a9 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604
  maxcompute_table_xxpt_it_ads_ods_ism_it_software_key_pool_df_07e571 --> maxcompute_table_xxpt_it_ads_ads_is_it_software_key_released_recycled_df_476604