package com.alibaba.qwen.code.managedworkspace;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Runs the language-neutral W0a fixtures that the TypeScript implementation
 * runs too. The fixtures were generated by an independent implementation of
 * the design document, so both languages are checked against a third one.
 */
class ManagedWorkspaceBindingConformanceTest {
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Pattern DECIMAL = Pattern.compile("[1-9][0-9]{0,18}");

    @Test
    void pinsTheDigestConstruction() throws IOException {
        JsonNode digest = fixtures().required("digest");

        assertEquals(1, fixtures().required("contractVersion").intValue());
        assertEquals("sha256", digest.required("algorithm").textValue());
        assertEquals("sha256:", digest.required("prefix").textValue());
        assertEquals(ContextBinding.DOMAIN_TAG,
                digest.required("domainTag").textValue());
        List<String> fieldOrder = new ArrayList<>();
        digest.required("fieldOrder").forEach(
                field -> fieldOrder.add(field.textValue()));
        assertEquals(List.of("tenantId", "workspaceId", "workspaceGeneration",
                "storageId", "cwdRelative", "contextConfigRef",
                "contextRevision"), fieldOrder);
    }

    @Test
    void normalizesEverySharedPathCase() throws IOException {
        int valid = 0;
        for (JsonNode fixture : fixtures().required("paths")) {
            String id = fixture.required("id").textValue();
            String input = fixture.required("input").textValue();
            JsonNode expected = fixture.required("expected");
            if (expected.has("cwdRelative")) {
                assertEquals(expected.required("cwdRelative").textValue(),
                        WorkspaceRelativePath.normalize(input), id);
                valid++;
            } else {
                assertEquals("invalid_cwd",
                        expected.required("error").textValue(), id);
                WorkspaceException error = assertThrows(
                        WorkspaceException.class,
                        () -> WorkspaceRelativePath.normalize(input), id);
                assertEquals("invalid_cwd", error.getCode(), id);
            }
        }
        assertTrue(valid > 0);
    }

    @Test
    void encodesAndDigestsEverySharedBindingCase() throws IOException {
        int valid = 0;
        for (JsonNode fixture : fixtures().required("bindings")) {
            String id = fixture.required("id").textValue();
            JsonNode binding = fixture.required("binding");
            JsonNode expected = fixture.required("expected");
            if (expected.has("contextDigest")) {
                ContextBinding built = build(binding);
                assertEquals(expected.required("encodedHex").textValue(),
                        HexFormat.of().formatHex(built.encode()), id);
                assertEquals(expected.required("contextDigest").textValue(),
                        built.getContextDigest(), id);
                valid++;
            } else {
                assertEquals("invalid_binding",
                        expected.required("error").textValue(), id);
                assertThrows(IllegalArgumentException.class,
                        () -> build(binding), id);
            }
        }
        assertTrue(valid > 0);
    }

    @Test
    void usesEachCaseIdOnce() throws IOException {
        Set<String> ids = new HashSet<>();
        for (String list : List.of("paths", "bindings")) {
            for (JsonNode fixture : fixtures().required(list)) {
                String id = fixture.required("id").textValue();
                assertTrue(ids.add(id), () -> "duplicate fixture id: " + id);
            }
        }
    }

    // Java carries generations and revisions as long, so a non-canonical
    // decimal cannot reach ContextBinding; reject it where the wire text is
    // parsed, exactly as a wire decoder would.
    private static ContextBinding build(JsonNode binding) {
        return new ContextBinding(binding.required("tenantId").textValue(),
                binding.required("workspaceId").textValue(),
                decimal(binding.required("workspaceGeneration").textValue()),
                binding.required("storageId").textValue(),
                binding.required("cwdRelative").textValue(),
                binding.required("contextConfigRef").textValue(),
                decimal(binding.required("contextRevision").textValue()));
    }

    private static long decimal(String value) {
        if (!DECIMAL.matcher(value).matches()) {
            throw new IllegalArgumentException("not a canonical decimal");
        }
        try {
            return Long.parseLong(value);
        } catch (NumberFormatException exception) {
            throw new IllegalArgumentException("decimal exceeds 64 bits",
                    exception);
        }
    }

    private static JsonNode fixtures() throws IOException {
        Path path = contractDirectory().resolve(
                "managed-workspace-binding-v1.fixtures.json");
        assertTrue(Files.isRegularFile(path),
                () -> "missing shared contract: " + path);
        return JSON.readTree(path.toFile());
    }

    private static Path contractDirectory() {
        Path current = Path.of(System.getProperty("user.dir")).toAbsolutePath();
        for (int depth = 0; depth < 6 && current != null; depth++) {
            Path candidate = current.resolve(Path.of("packages", "cli", "src",
                    "serve", "contracts"));
            if (Files.isDirectory(candidate)) {
                return candidate;
            }
            current = current.getParent();
        }
        throw new AssertionError("cannot locate the shared contract fixtures");
    }
}
